name: teletubies-main
on:
   workflow_dispatch:

env:
  TZ: Asia/Jakarta
  
jobs:
  teletubiesbuild:
       runs-on: ubuntu-22.04

       steps:
       - name: Creating env!
         uses: actions/checkout@v2

       - name: Setting up env!
         run: |
          git clone https://github.com/akhilnarang/scripts x
          cd x/setup && bash android_build_env.sh
       - name: Building Kernel...
         run: |
             chmod +x build.sh && bash build.sh
             shell: bash
             env:
              CHATID: ${{ secrets.CHAT_ID }}
              API_BOT: ${{ secrets.BOT_API }}

